### ISSUE TITLE
Supporter / sponsor table looks like shit

### ISSUE THREAD

**Issue by who1s** [HelSec/website#16]
![image](https://user-images.githubusercontent.com/24723281/162764842-d295a0ae-4c1a-44e7-bde0-a1e62a6e28bf.png)

Rowing in `/main/themes/helsec/layouts/partials/supporters.html` doesn't work properly. Also CSS should be fixed that the rows are aligned vertically.

Anyone up for help?

**Comment by korteke** [comment]
This is fixed by making a 500x300px transparent template image where we put company logo. This ensures proper spacing and eliminates the need to juggle with the Hugo template. Logos come in all sizes so this is the easiest way.

<img width="1145" alt="image" src="https://github.com/HelSec/website/assets/2558348/a2dbcc1d-a3b6-4324-92fc-602eeabfe208">
